
server:
  port: 8080

spring:
  application:
    name: mate-service
  config:
    import : secret/application-secret.yml




#
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



